name: SonarQube Analysis

on:
  push:
    branches: [main, master, develop]
  pull_request:
    branches: [main, master]

jobs:
  sonar-auth-service:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Scan auth-service
        run: |
          docker run --rm \
            -v taller-sast-sonar_runner_data:/tmp/runner \
            -w /tmp/runner/taller-sast-sonar \
            --network taller-sast-sonar_devsecops \
            sonarsource/sonar-scanner-cli \
            sonar-scanner \
              -Dsonar.projectKey=auth-service \
              -Dsonar.sources=apps/auth-service/src \
              -Dsonar.host.url=http://sonarqube:9000 \
              -Dsonar.login=${{ secrets.SONAR_TOKEN }}

  sonar-products:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Scan products
        run: |
          docker run --rm \
            -v taller-sast-sonar_runner_data:/tmp/runner \
            -w /tmp/runner/taller-sast-sonar \
            --network taller-sast-sonar_devsecops \
            sonarsource/sonar-scanner-cli \
            sonar-scanner \
              -Dsonar.projectKey=products \
              -Dsonar.sources=apps/products/src \
              -Dsonar.host.url=http://sonarqube:9000 \
              -Dsonar.login=${{ secrets.SONAR_TOKEN }}

  sonar-frontend:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Scan frontend
        run: |
          docker run --rm \
            -v taller-sast-sonar_runner_data:/tmp/runner \
            -w /tmp/runner/taller-sast-sonar \
            --network taller-sast-sonar_devsecops \
            sonarsource/sonar-scanner-cli \
            sonar-scanner \
              -Dsonar.projectKey=frontend \
              -Dsonar.sources=apps/frontend/src \
              -Dsonar.host.url=http://sonarqube:9000 \
              -Dsonar.login=${{ secrets.SONAR_TOKEN }}

  sonar-analisis-vulnerabilidades:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Scan analisis-vulnerabilidades
        run: |
          docker run --rm \
            -v taller-sast-sonar_runner_data:/tmp/runner \
            -w /tmp/runner/taller-sast-sonar \
            --network taller-sast-sonar_devsecops \
            sonarsource/sonar-scanner-cli \
            sonar-scanner \
              -Dsonar.projectKey=analisis-vulnerabilidades \
              -Dsonar.sources=apps/analisis-vulnerabilidades/backend,apps/analisis-vulnerabilidades/frontend \
              -Dsonar.host.url=http://sonarqube:9000 \
              -Dsonar.login=${{ secrets.SONAR_TOKEN }}
